name: Discord Webhook (Final)

on: [push]

jobs:
  Discord_notification:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout (No cambia)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Preparar Mensaje (CORREGIDO)
      - name: Prepare Discord Message
        id: prep_message
        run: |
          COMMITS_JSON='${{ toJSON(github.event.commits) }}'
          DESCRIPTION_TEXT=""
          for sha in $(echo "$COMMITS_JSON" | jq -r '.[].id'); do
            COMMIT_MESSAGE=$(git log --format=%s -n 1 "$sha")
            COMMIT_AUTHOR=$(git log --format=%an -n 1 "$sha")
            DESCRIPTION_TEXT+=$(printf "✍️ **%s** - *%s*\\n" "$COMMIT_MESSAGE" "$COMMIT_AUTHOR")
            
            FILE_CHANGES_FORMATTED=""

            while read -r status file; do
              # ✅ CORRECCIÓN: Se elimina la palabra 'local'
              file_emoji="📄"
              case "$file" in
                *.java)         file_emoji="☕" ;;
                *.yml|*.yaml)   file_emoji="📝" ;;
                *.xml|*.pom)    file_emoji="⚙️" ;;
                *.md)           file_emoji="ℹ️" ;;
                *.png|*.jpg)    file_emoji="🖼️" ;;
              esac

              # ✅ CORRECCIÓN: Se elimina la palabra 'local'
              diff_prefix=" "
              case "$status" in
                A) diff_prefix="+" ;;
                D) diff_prefix="-" ;;
              esac

              FILE_CHANGES_FORMATTED+=$(printf "%s %s %s\\n" "$diff_prefix" "$file_emoji" "$file")
            done < <(git show --name-status --pretty="" "$sha")

            if [[ -n "$FILE_CHANGES_FORMATTED" ]]; then
              DESCRIPTION_TEXT+=$(printf '```diff\n%s\n```\n' "$FILE_CHANGES_FORMATTED")
            fi
          done

          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$DESCRIPTION_TEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Paso 3: Enviar Webhook (No cambia)
      - name: Send Discord Webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "GitHub"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          embed-title: "📦 Push a `${{ github.ref_name }}` (${{ github.event.commits_count }} nuevos commits)"
          embed-description: ${{ steps.prep_message.outputs.description }}
          embed-color: "3447003"
          embed-timestamp: ${{ job.started_at }}
          embed-author-name: ${{ github.actor }}
          embed-author-url: "https://github.com/${{ github.actor }}"
          embed-author-icon-url: "https://github.com/${{ github.actor }}.png"