name: Discord Notification (curl)

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs | sed 's/ /\\n/g')" >> $GITHUB_OUTPUT

      - name: Send webhook with curl
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "BetterGithub",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "📦 Commit agregado a `main`",
                "description": "[\"${{ github.event.head_commit.message }}\"](${{ github.event.head_commit.url }}) - ${{ github.actor }}",
                "color": 15844367,
                "fields": [{
                  "name": "Archivos modificados",
                  "value": "```diff\n${{ steps.changes.outputs.files }}```"
                }],
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}